# Cloud Build configuration for Google Cloud Run
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/semantic-search-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/semantic-search-backend:latest'
      - './backend'
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/semantic-search-backend:$COMMIT_SHA'
    id: 'push-image'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'semantic-search-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/semantic-search-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
    id: 'deploy-cloud-run'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/semantic-search-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/semantic-search-backend:latest'

# Build timeout
timeout: 1200s

# Options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
